// apps/web/app/components/scroll-header.vue
<script setup>
import { onBeforeUnmount, onMounted, ref } from 'vue'

const isScrolled = ref(false)

const onScroll = () => {
  const scrollY =
    typeof globalThis === 'object' && 'scrollY' in globalThis
      ? Number(globalThis.scrollY)
      : 0
  isScrolled.value = scrollY > 12
}

onMounted(() => {
  onScroll()
  if (typeof globalThis.addEventListener === 'function') {
    globalThis.addEventListener('scroll', onScroll, { passive: true })
  }
})

onBeforeUnmount(() => {
  if (typeof globalThis.removeEventListener === 'function') {
    globalThis.removeEventListener('scroll', onScroll)
  }
})
</script>

<template>
  <header
    :class="[
      'sticky top-0 z-50 border-b transition-all',
      isScrolled
        ? 'bg-white/90 backdrop-blur supports-[backdrop-filter]:bg-white/60'
        : 'bg-white',
    ]"
  >
    <MaxWidthWrapper class-name="flex h-16 items-center justify-between">
      <a href="#" class="text-lg font-bold tracking-tight">yoguhaeyo</a>
      <nav
        class="hidden items-center gap-6 text-sm font-medium text-gray-600 md:flex"
      >
        <a href="#features" class="hover:text-foreground">기능</a>
      </nav>
    </MaxWidthWrapper>
  </header>
</template>

// app/components/scroll-header.jsx
"use client"

import { useState, useEffect } from 'react';
import Link from 'next/link';
import GithubLoginButton from '@/components/github-login-button';

const MaxWidthWrapper = ({ children, className }) => (
  <div className={`mx-auto w-full max-w-7xl px-4 md:px-8 lg:px-12 ${className}`}>
    {children}
  </div>
);

const ScrollHeader = () => {
  const [scrolled, setScrolled] = useState(false);

  useEffect(() => {
    const handleScroll = () => {
      setScrolled(window.scrollY > 1);
    };

    window.addEventListener('scroll', handleScroll);

    return () => {
      window.removeEventListener('scroll', handleScroll);
    };
  }, []);

  const headerClasses = `h-16 flex items-center justify-center sticky top-0 z-50 transition-all duration-300 ${
    scrolled
      ? 'border-b border-gray-100 bg-white/50 backdrop-blur-lg shadow-sm'
      : 'bg-white/0'
  }`;

  const buttonClasses = `transition-all duration-300 ${
    scrolled
      ? 'border bg-white/20 backdrop-blur-lg shadow-sm'
      : ''
  }`;

  return (
    <header className={headerClasses}>
      <MaxWidthWrapper className="flex items-center justify-between">
        <Link className="flex items-center justify-center" href="/">
          <span className="font-extrabold text-xl tracking-tight">yoguhaeyo</span>
        </Link>
        <nav className="ml-auto flex items-center gap-6">
          <Link className="text-sm font-medium hover:text-primary transition-colors" href="#features">
              기능
          </Link>
          <GithubLoginButton variant="outline" text="로그인" cName={buttonClasses} /> 
        </nav>
      </MaxWidthWrapper>
    </header>
  );
};

export default ScrollHeader;
